name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  jazz-frontend:
    uses: k3aix/aac-k3s/.github/workflows/docker-multiarch-build.yml@main
    with:
      service: jazz-frontend
      context: frontend
      push: ${{ github.event_name != 'pull_request' }}

  jazz-standards:
    uses: k3aix/aac-k3s/.github/workflows/docker-multiarch-build.yml@main
    with:
      service: jazz-standards
      context: backend/standards-service
      push: ${{ github.event_name != 'pull_request' }}

  jazz-search:
    uses: k3aix/aac-k3s/.github/workflows/docker-multiarch-build.yml@main
    with:
      service: jazz-search
      context: backend/search-service/SearchService
      push: ${{ github.event_name != 'pull_request' }}
